drop policy "Enable delete for users based on user_id" on "public"."groups";

drop policy "Enable insert for users based on user_id" on "public"."groups";

drop policy "Enable read access for all users" on "public"."groups";

drop policy "Enable insert for users based on user_id" on "public"."attendance";

revoke delete on table "public"."groups" from "anon";

revoke insert on table "public"."groups" from "anon";

revoke references on table "public"."groups" from "anon";

revoke select on table "public"."groups" from "anon";

revoke trigger on table "public"."groups" from "anon";

revoke truncate on table "public"."groups" from "anon";

revoke update on table "public"."groups" from "anon";

revoke delete on table "public"."groups" from "authenticated";

revoke insert on table "public"."groups" from "authenticated";

revoke references on table "public"."groups" from "authenticated";

revoke select on table "public"."groups" from "authenticated";

revoke trigger on table "public"."groups" from "authenticated";

revoke truncate on table "public"."groups" from "authenticated";

revoke update on table "public"."groups" from "authenticated";

revoke delete on table "public"."groups" from "service_role";

revoke insert on table "public"."groups" from "service_role";

revoke references on table "public"."groups" from "service_role";

revoke select on table "public"."groups" from "service_role";

revoke trigger on table "public"."groups" from "service_role";

revoke truncate on table "public"."groups" from "service_role";

revoke update on table "public"."groups" from "service_role";

alter table "public"."groups" drop constraint "classes_admin_fkey";

alter table "public"."attendance" drop constraint "attendance_student_fkey";

alter table "public"."codes" drop constraint "codes_class_fkey";

alter table "public"."students" drop constraint "students_class_fkey";

alter table "public"."students" drop constraint "students_student_fkey";

alter table "public"."groups" drop constraint "classes_pkey";

alter table "public"."attendance" drop constraint "attendance_pkey";

alter table "public"."students" drop constraint "students_pkey";

drop index if exists "public"."attendance_pkey";

drop index if exists "public"."classes_pkey";

drop index if exists "public"."students_pkey";

drop table "public"."groups";

create table "public"."classes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "admin" uuid not null,
    "name" text not null,
    "config" jsonb default 'null'::jsonb
);


alter table "public"."attendance" drop column "attendee";

alter table "public"."attendance" add column "student" uuid not null;

alter table "public"."codes" drop column "group";

alter table "public"."codes" add column "class" bigint not null;

alter table "public"."students" drop column "attendee";

alter table "public"."students" drop column "group";

alter table "public"."students" add column "class" bigint not null;

alter table "public"."students" add column "student" uuid not null;

CREATE UNIQUE INDEX attendance_pkey ON public.attendance USING btree (student, code_used);

CREATE UNIQUE INDEX classes_pkey ON public.classes USING btree (id);

CREATE UNIQUE INDEX students_pkey ON public.students USING btree (student, class);

alter table "public"."classes" add constraint "classes_pkey" PRIMARY KEY using index "classes_pkey";

alter table "public"."attendance" add constraint "attendance_pkey" PRIMARY KEY using index "attendance_pkey";

alter table "public"."students" add constraint "students_pkey" PRIMARY KEY using index "students_pkey";

alter table "public"."classes" add constraint "classes_admin_fkey" FOREIGN KEY (admin) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."classes" validate constraint "classes_admin_fkey";

alter table "public"."attendance" add constraint "attendance_student_fkey" FOREIGN KEY (student) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."attendance" validate constraint "attendance_student_fkey";

alter table "public"."codes" add constraint "codes_class_fkey" FOREIGN KEY (class) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."codes" validate constraint "codes_class_fkey";

alter table "public"."students" add constraint "students_class_fkey" FOREIGN KEY (class) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."students" validate constraint "students_class_fkey";

alter table "public"."students" add constraint "students_student_fkey" FOREIGN KEY (student) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."students" validate constraint "students_student_fkey";

grant delete on table "public"."classes" to "anon";

grant insert on table "public"."classes" to "anon";

grant references on table "public"."classes" to "anon";

grant select on table "public"."classes" to "anon";

grant trigger on table "public"."classes" to "anon";

grant truncate on table "public"."classes" to "anon";

grant update on table "public"."classes" to "anon";

grant delete on table "public"."classes" to "authenticated";

grant insert on table "public"."classes" to "authenticated";

grant references on table "public"."classes" to "authenticated";

grant select on table "public"."classes" to "authenticated";

grant trigger on table "public"."classes" to "authenticated";

grant truncate on table "public"."classes" to "authenticated";

grant update on table "public"."classes" to "authenticated";

grant delete on table "public"."classes" to "service_role";

grant insert on table "public"."classes" to "service_role";

grant references on table "public"."classes" to "service_role";

grant select on table "public"."classes" to "service_role";

grant trigger on table "public"."classes" to "service_role";

grant truncate on table "public"."classes" to "service_role";

grant update on table "public"."classes" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."classes"
as permissive
for delete
to public
using ((auth.uid() = admin));


create policy "Enable insert for users based on user_id"
on "public"."classes"
as permissive
for insert
to public
with check ((auth.uid() = admin));


create policy "Enable read access for all users"
on "public"."classes"
as permissive
for select
to public
using (true);


create policy "Enable insert for users based on user_id"
on "public"."attendance"
as permissive
for insert
to public
with check ((auth.uid() = student));
