on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
name: Generate Snapshots
jobs:
  generate:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Supabase v1.123.4
        uses: supabase/setup-cli@v1
        with:
          version: 1.123.4
      - name: Set up Supabase
        run: |
          supabase start
          supabase status -o env | sed s/API_URL/NEXT_PUBLIC_SUPABASE_URL/g | sed s/ANON_KEY/NEXT_PUBLIC_SUPABASE_ANON_KEY/g > .env.local
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Build project
        run: bun run build
      - name: Run Playwright tests
        run: bun run test --update-snapshots
      - uses: actions/upload-artifact@v3
        with:
          name: Snapshots
          path: |
            tests/**/*.ts-snapshots/
